/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

/******************************************************************************/

#include <stdio.h>

#define Set(Register_name,bit_no)     Register_name|=(1<<bit_no)    //to set bit
#define Reset(Register_name,bit_no)   Register_name&=~(1<<bit_no)   //to reset bit

typedef volatile unsigned int vuint32_t ;

//RCC reset and clock control address
#define RCC          0x40021000

//RCC_CFGR Clock configuration register address
#define RCC_CFGR     *( vuint32_t *)( RCC + 0x04 )

//RCC_CR Clock control register address
#define RCC_CR       *( vuint32_t *)( RCC + 0x00 )

void Init_HSI_Clock()
{
	//Set system clock to 32 MHZ
	//Select PLL as a system clock by write 10 on SYSCLK(bits 1:0)
	Set(RCC_CFGR,1);

	//PLL entry clock source
	//By default PLLSRC is selected HSI oscillator clock as PLL input clock

	//PLL multiplication factor
	//Muliple by 8 by write 0110 on PLLMUL(bits 21:18)
	Set(RCC_CFGR,20);
	Set(RCC_CFGR,19);

	//AHB Prescaler
	//BY default divide by 1 by write 0000 on HPRE:(bits 7:4)

	//Set APB1 Prescaler to 16 MHZ
	//divide by 2 by write 100 on PPRE1(bits 10:8)
	Set(RCC_CFGR,10);

	//Set APB2 Prescaler to 8 MHZ
	//divide by 4 by write 101 on PPRE2(bits 13:11)
	Set(RCC_CFGR,13);
	Set(RCC_CFGR,11);

	//PLL Enable
	Set(RCC_CR,24);

	return;
}

int main()
{
	//INIT HSI Clock
	Init_HSI_Clock();

	while(1);

	return 0;
}
