/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

/******************************************************************************/

#include <stdio.h>

#define Set(Register_name,bit_no)     Register_name|=(1<<bit_no)    //to set bit
#define Reset(Register_name,bit_no)   Register_name&=~(1<<bit_no)   //to reset bit

typedef volatile unsigned int vuint32_t ;

//RCC reset and clock control address
#define RCC          0x40021000

//RCC_CFGR Clock configuration register address
#define RCC_CFGR     *( vuint32_t *)( RCC + 0x04 )

void Init_HSI_Clock()
{
	//MCO Microcontroller clock output
	//Select HSI_RC Internal Clock
	Set(RCC_CFGR,24);
	Set(RCC_CFGR,26);

	//Set SYSCLK to 8MHZ
	Reset(RCC_CFGR,0);
	Reset(RCC_CFGR,1);

	//Set PPRE1 APB1 Prescaler to 4MHZ
	//divide by 2
	Set(RCC_CFGR,10);

	//Set PPRE2 APB2 Prescaler to 2MHZ
	//divide by 4
	Set(RCC_CFGR,11);
	Set(RCC_CFGR,13);

	return;
}

int main()
{
	//INIT HSI Clock
	Init_HSI_Clock();

	while(1);

	return 0;
}
